"""
Django settings for transaction_data_analysis project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import os
from main.utils.logger_config import set_logger

#Initialise custom logger object
ic = set_logger(print_to_console=False)

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG_MODE")

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",  # new
    "django_bootstrap5", #django-bootstrap5 
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_auto_logout.middleware.auto_logout",

]

ROOT_URLCONF = "transaction_data_analysis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [ BASE_DIR / "main/templates" ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # "django_auto_logout.context_processors.auto_logout_client",
            ],
        },
    },
]

WSGI_APPLICATION = "transaction_data_analysis.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / f"{os.getenv("DATABASE_NAME")}.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "main/static/"
STATICFILES_DIRS = [BASE_DIR / "main/static"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Base directory for media files
MEDIA_URL = "main/media/"
MEDIA_ROOT = BASE_DIR / "main/media"

# django-auto-logout config
AUTO_LOGOUT = {
    "IDLE_TIME": timedelta(minutes=10),
    "SESSION_TIME": timedelta(minutes=60),
    "REDIRECT_TO_LOGIN_IMMEDIATELY": True,
    "MESSAGE": "Your session has expired, please login again to continue.",
}

LOGIN_URL = "login"
LOGOUT_REDIRECT_URL = "/"

# Project logs
TRANSACTION_DATA_ANALYSIS_PATH = BASE_DIR / "logs/transaction_data_analysis.log"
MAIN_LOG_FILE_PATH = BASE_DIR / "main/logs/main.log"

# Check and create directories if they don't exist
for log_path in [TRANSACTION_DATA_ANALYSIS_PATH, MAIN_LOG_FILE_PATH]:
    directory = log_path.parent
    if not directory.is_dir():
        directory.mkdir(parents=True, exist_ok=True)
        ic("Parent directories for .log files not found, creating manually.")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
           "class": "logging.StreamHandler",
           "formatter": "verbose",
       },
        "project_file": {
            "class": "logging.FileHandler",
            "filename": TRANSACTION_DATA_ANALYSIS_PATH,
            "formatter": "verbose",
        },
        "app_file": {
            "class": "logging.FileHandler",
            "filename": MAIN_LOG_FILE_PATH,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "project": {
            "level": "DEBUG",
            "handlers":  ["project_file"], # Use ["project_file", "console"] if console output is to be enabled 
        },
        "main": {
            "level": "DEBUG",
            "handlers":  ["app_file"], # Use ["project_file", "console"] if console output is to be enabled 
        },
    },
}
